Reduce the squashfs block size when using zstd
puppylinux-woof-CE/woof-CE pull request #2272
Opened 2021-05-19 17:53 UTC by dimkr

https://forum.puppylinux.com/viewtopic.php?p=25809#p25809

2021-05-20 09:34 UTC, 01micko requested changes
Please change slacko and slacko64 based on slackware 14.2 back to xz compression for squash please Yes I know it messes up the CI too.

2021-05-20 09:34 UTC, 01micko commented on woof-distro/x86/slackware/14.2/_00build.conf
> +SFSCOMP='-comp zstd -Xcompression-level 19 -b 256K'
A problem with slackware(64)-14.2 is lack of support for `zstd` due to the age. I should have mentioned this awhile ago. Sorry!

2021-05-20 15:40 UTC, dimkr commented on woof-distro/x86/slackware/14.2/_00build.conf
> +SFSCOMP='-comp zstd -Xcompression-level 19 -b 256K'
I've tested it with 4.19.x, and it boots just fine!

```
$ grep SQUASHFS_ZSTD kernel-kit/configs_x86*/DOTconfig-4.19* | grep =y
woof-CE/kernel-kit/configs_x86_64/DOTconfig-4.19.160-x86_64:CONFIG_SQUASHFS_ZSTD=y
woof-CE/kernel-kit/configs_x86/DOTconfig-4.19.160-i686-pae:CONFIG_SQUASHFS_ZSTD=y
```

Both 32-bit and 64-bit.

2021-05-21 09:49 UTC, 01micko commented on woof-distro/x86/slackware/14.2/_00build.conf
> +SFSCOMP='-comp zstd -Xcompression-level 19 -b 256K'
It's not a kernel issue at all - userspace. `zstd` compressed sfs mount and unmount just fine - but try to squash or unsquash with `zstd`. Slacko-7.0x must be able to build itself!

There is no `zstd` support _at all_ in slackware-14.2.

2021-05-21 19:19 UTC, merged

2021-05-25 18:21 UTC, peabee commented
Rockedge has problem building FossaPup64 using BionicPup64 as it doesn't have zstd....
https://forum.puppylinux.com/viewtopic.php?p=26333#p26333

2021-05-25 18:38 UTC, dimkr commented
If you ask me, it's unrealistic to build 2020 tech on a 2018 distro, and super unrealistic to expect woof-CE developers to test it on an old distro with 3+ years old packages