Create service2initd
puppylinux-woof-CE/woof-CE pull request #2395
Opened 2021-07-19 05:45 UTC by rizalmart

This script generates init.d script from systemd .service file. Because some distros are now longer provides init.d scripts.

2021-07-24 02:47 UTC, 01micko commented
I've asked @dimkr to review this PR as I don't use any systemd distro and am not familiar with the file formats.

2021-09-07 09:54 UTC, 01micko commented
@dimkr ?

2021-09-07 10:48 UTC, dimkr requested changes

2021-09-07 10:48 UTC, dimkr commented on woof-code/rootfs-skeleton/usr/bin/service2initd
> +SRVFILE="$1"
There's a messy mix of spaces and tabs in this file

2021-09-07 10:48 UTC, dimkr commented on woof-code/rootfs-skeleton/usr/bin/service2initd
> + exit
exit 1?

2021-09-07 10:48 UTC, dimkr commented on woof-code/rootfs-skeleton/usr/bin/service2initd
> +	 WKDIR="$(cat $SRVFILE | grep '^WorkingDirectory=' | cut -f 2 -d '=' | xargs)"
This list of fields is partial - for example, Restart= is not taken care of and doesn't translate well to sysvinit

2021-09-07 10:48 UTC, dimkr commented on woof-code/rootfs-skeleton/usr/bin/service2initd
> +      echo ' '$ENV_VALUES' '$EXECCMD''$BCKPID
Are you assuming that EXECCMD will daemonize? In the systemd world, not daemonizing (so systemd can restart you) is the norm

2021-09-07 10:48 UTC, dimkr commented on woof-code/rootfs-skeleton/usr/bin/service2initd
> +#!/bin/bash
What uses this script? What is the % of successful translation?

2021-10-17 08:49 UTC, closed without merging