quicksetup: make it work in pure wayland and improve gtk3 performance
puppylinux-woof-CE/woof-CE pull request #2922
Opened 2022-02-27 11:54 UTC by 01micko

re: #2903

This is a big commit so I will provide the file for testing in a zip

Changes:
- fix some actions on 'OK' press
- suppress 'xset' under wayland
- test for DISPLAY and WAYLAND_DISPLAY for GUI
- add test for numlockt (alternative to numlockx)
- fix LANG=C bug asking for translation
- add 'change root password' checkbox
- fix numerous logic bugs
- remove comboboxtext in favour of a button to launch a 'tree' widget
for locale, timezone, keyboard and crdw choices. It is much better under
gtk3, fixes quicksetup under wayland, and works great in gtk2
- remove redundant, useless stuff

2022-02-27 11:58 UTC, 01micko commented
As promised, attached is a zip file

[qs.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/8148593/qs.zip)

Try it in a running Pup, or use it to build. Easier than reviewing, but **by all means** review this if yo're up for it.

2022-02-27 14:51 UTC, peabee requested changes
There is no way to select the chosen value in the multi-choice drop down lists - no "Select" or "OK" button........

2022-02-27 16:56 UTC, dimkr commented
One of the things I have about quicksetup is the huge number of features in one thing. It will take time to test every single feature in each scenario (X, Xwayland and labwc) 😠

But it's great to finally fix all these issues! It's a mess.

2022-02-27 20:14 UTC, 01micko commented
> There is no way to select the chosen value in the multi-choice drop down lists - no "Select" or "OK" button........

There is an OK button at the bottom! Or does it go off screen for you? I can reduce the height.

2022-02-27 23:08 UTC, peabee commented
No sign of any button here......
And "Enter" does not work so any hidden button must not have focus.....
Tried double click of entry as well - that also didn't work

2022-02-27 23:27 UTC, 01micko commented
This is in gtk2. There are _no_ hidden buttons. In fact this isn't the version you have because I made the OK button huge

![qs2-3](https://user-images.githubusercontent.com/1019119/155904513-67530acb-6652-49ad-ab16-7cdcdb09863e.png)
.

2022-02-28 01:22 UTC, closed without merging

2022-02-28 01:32 UTC, 01micko commented
I messed something up in my repo, fixed in new PR