Add the Numix JWM themes from BionicPup and FossaPup
puppylinux-woof-CE/woof-CE pull request #3663
Opened 2022-11-27 16:57 UTC by dimkr

2022-11-27 17:45 UTC, lakshayrohila requested changes
I have missed Numix theme! Thanks for this PR!

Just an issue here - there is no newline at the end of the files. It is not much of an issue though, still a POSIX standard.

2022-11-27 17:48 UTC, dimkr commented
> a POSIX standard.

For C source code, not XML :)

2022-11-27 17:51 UTC, lakshayrohila commented
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

The first answer is your answer too!

2022-11-27 17:54 UTC, lakshayrohila approved these changes

2022-11-28 09:25 UTC, 01micko approved these changes

2022-11-28 17:28 UTC, merged